name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: ui_organizer.sln

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        $ver = vswhere.exe -latest -format value -property catalog_productLineVersion
        if ("2019" -eq $ver)
        {
          msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}} /p:PlatformToolset=v142
          msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PlatformToolset=v142
        }
        elseif ("2022" -eq $ver)
        {
          msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}} /p:PlatformToolset=v143
          msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PlatformToolset=v143 
        }
        else
        {
          $message = "Unknown version of Visual Studio used - '{0}'." -f $ver
          Write-Warning -Message $message
          msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}}
          msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}
        }

    - name: Upload binaries
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artifact
        path: |
          ${{github.workspace}}/Debug
          ${{github.workspace}}/Release
