name: MSBuild

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: ui_organizer.sln

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: windows-2016
          PlatformToolset: v141
          WindowsTargetPlatformVersion: 8.1
        - os: windows-2019
          PlatformToolset: v142
          WindowsTargetPlatformVersion: 10.0
        - os: windows-2022
          PlatformToolset: v143
          WindowsTargetPlatformVersion: 10.0

        # windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    #- name: TMP Patch
    #  run: git checkout ui_organizer -- .

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build (Debug)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}} /p:PlatformToolset=${{matrix.PlatformToolset}} /p:WindowsTargetPlatformVersion=${{matrix.WindowsTargetPlatformVersion}}

    - name: Build (Release)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PlatformToolset=${{matrix.PlatformToolset}} /p:WindowsTargetPlatformVersion=${{matrix.WindowsTargetPlatformVersion}}

    - name: Upload binaries
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artifact-toolset_${{matrix.PlatformToolset}}
        path: |
          ${{github.workspace}}/Debug
          ${{github.workspace}}/Release
